---

STA_SSID1: '${WIFI_SSID}'
STA_PASS1: '${WIFI_PASS}'

OTA_URL: '${OTA_URL}'

MQTT_HOST: '${MQTT_HOST}'
MQTT_USER: '${MQTT_USER}'
MQTT_PASS: '${MQTT_PASS}'
MQTT_TOPIC: '"unconfigured"'

TELE_PERIOD: '30'

USE_DOMOTICZ: '!undef'
USE_HOME_ASSISTANT: '!undef'
USE_EMULATION: '!undef'
USE_DISCOVERY: '!undef'

NTP_SERVER1: '"ptbtime1.ptb.de"'
NTP_SERVER2: '"ptbtime2.ptb.de"'

USE_IR_REMOTE: '!undef'
USE_WS2812: '!undef'
USE_ARILUX_RF: '!undef'

...
